name: Lydia CI pipeline

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  lint:
    continue-on-error: true
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get install -y clang-format-9
    - name: Check File Headers
      run: python3 ./scripts/check_copyright_notice.py
    - name: Check clang-format
      run: ./scripts/check-clang-format.sh

  # Test the build of all the targets works.
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]  # TODO include macos-latest, windows-latest
        compiler: [g++-9]

    continue-on-error: true
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy-9
          sudo apt-get install -y wget

          # install flex/bison
          sudo apt-get purge -y flex
          sudo apt-get purge -y bison
          sudo apt-get install -y flex bison
          sudo apt-get autoremove

          # install boost
          sudo apt-get install -y libboost-dev

          sudo apt-get install -y graphviz libgraphviz-dev
          sudo python3 -m pip install gcovr
      - name: Check clang-tidy
        run: ./scripts/check-clang-tidy.sh
      - name: Install dependencies
        run: sudo ./scripts/_ci-install-dependencies-ubuntu.sh
      - name: Configure CMake
        env:
          CXX: ${{ matrix.compiler }}
        run: ./scripts/_ci-configure.sh
      - name: Build library
        run: cd build && VERBOSE=1 make lydia -j
      - name: Build app
        run: cd build && VERBOSE=1 make lydia-bin -j
      - name: Build benchmarks
        run: cd build && VERBOSE=1 make lydiaBench -j

  # Build and run the tests.
  test:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]  # TODO include macos-latest, windows-latest
        compiler: [ g++-9 ]

    continue-on-error: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy-9
          sudo apt-get install -y wget git cmake

          # install flex/bison
          sudo apt-get purge -y flex
          sudo apt-get purge -y bison
          sudo apt-get install -y flex bison
          sudo apt-get autoremove

          # install boost
          sudo apt-get install -y libboost-dev

          sudo apt-get install -y graphviz libgraphviz-dev
          sudo python3 -m pip install gcovr
      - name: Install dependencies
        run: sudo ./scripts/_ci-install-dependencies-ubuntu.sh
      - name: Configure CMake
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          echo "Configuring tests"
          ./scripts/_ci-configure.sh
      - name: Build
        run: |
          echo "Running tests"
          cd build && VERBOSE=1 make lydiaTest -j
      - name: Test
        run: ./scripts/_ci-test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
